### ISSUE TITLE
Secure Wiring

### ISSUE THREAD

**Issue by astronautlevel2** [Team2537/Cogsworth#5]
The ultrasonic came unplugged this competition and we consequentially missed an auto gear. The ultrasonic wire, as well as any other PWM wires used on the bot should be secured somehow.

**Comment by nfroggy** [comment]
how bout some scotch tape

**Comment by astronautlevel2** [comment]
We currently are holding it in place with duct tape. However, duct tape is not static proof so this is a less than optimal solution.

**Comment by nfroggy** [comment]
electrical tape is static proof, and we could always tape those bags that
they ship hard drives and stuff in around the wires

**Comment by astronautlevel2** [comment]
I was thinking electrical tape may be the best solution. I'll talk to Riddhi about it next meeting.

**Comment by astronautlevel2** [comment]
This is done
