### ISSUE TITLE
Side Peg Autonomous

### ISSUE THREAD

**Issue by astronautlevel2** [Team2537/Cogsworth#7]
Currently our bot is capable of placing a gear on the middle peg. We should focus on being able to place a gear on the side peg as well.

High level overview: 
* Drive forward using encoders
* Turn using NavX
* Turn more precisely using vision
* Drive forward using ultrasonic

**Comment by astronautlevel2** [comment]
This is now added in https://github.com/Team2537/Cogsworth/commit/2da9ba5ccaa0f87a3042f2de8ad12e38ba3f0848. Good work to Benji, @octapus (Arden), and @shicky256 (Nathan)!

**Comment by nfroggy** [comment]
No prob Bob.
Quick question: is it cool if the robot rams into the peg at full speed
during the competition? It means we can do a l/r peg in like 4.5 seconds

**Comment by astronautlevel2** [comment]
Well, that depends how the gear is placed. If Max can lift it then sure, go ahead.
